/* tslint:disable */
/* eslint-disable */
/**
 * bnm
 * Books N More's API
 *
 * OpenAPI spec version: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AdminBookByIdData
 */
export interface AdminBookByIdData {
    /**
     * 
     * @type {string}
     * @memberof AdminBookByIdData
     */
    ISBN?: any;
    /**
     * 
     * @type {string}
     * @memberof AdminBookByIdData
     */
    author?: any;
    /**
     * 
     * @type {number}
     * @memberof AdminBookByIdData
     */
    errorCode: any;
    /**
     * 
     * @type {number}
     * @memberof AdminBookByIdData
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof AdminBookByIdData
     */
    shelfCode?: any;
    /**
     * 
     * @type {string}
     * @memberof AdminBookByIdData
     */
    title?: any;
}
