/* tslint:disable */
/* eslint-disable */
/**
 * bnm
 * Books N More's API
 *
 * OpenAPI spec version: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AdminEditBookByIdBody
 */
export interface AdminEditBookByIdBody {
    /**
     * 
     * @type {string}
     * @memberof AdminEditBookByIdBody
     */
    ISBN: any;
    /**
     * 
     * @type {string}
     * @memberof AdminEditBookByIdBody
     */
    author: any;
    /**
     * 
     * @type {number}
     * @memberof AdminEditBookByIdBody
     */
    bookId: any;
    /**
     * 
     * @type {string}
     * @memberof AdminEditBookByIdBody
     */
    shelfCode: any;
    /**
     * 
     * @type {string}
     * @memberof AdminEditBookByIdBody
     */
    title: any;
    /**
     * 
     * @type {string}
     * @memberof AdminEditBookByIdBody
     */
    authKey: any;
}
