/* tslint:disable */
/* eslint-disable */
/**
 * bnm
 * Books N More's API
 *
 * OpenAPI spec version: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BookData
 */
export interface BookData {
    /**
     * 
     * @type {number}
     * @memberof BookData
     */
    id: any;
    /**
     * 
     * @type {string}
     * @memberof BookData
     */
    title: any;
    /**
     * 
     * @type {string}
     * @memberof BookData
     */
    author: any;
    /**
     * 
     * @type {number}
     * @memberof BookData
     */
    borrowedOn?: any;
    /**
     * 
     * @type {number}
     * @memberof BookData
     */
    canCancel?: any;
    /**
     * 
     * @type {string}
     * @memberof BookData
     */
    shelfCode?: any;
    /**
     * 
     * @type {number}
     * @memberof BookData
     */
    borrowerId?: any;
}
