/* tslint:disable */
/* eslint-disable */
/**
 * bnm
 * Books N More's API
 *
 * OpenAPI spec version: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CreateMemberInput
 */
export interface CreateMemberInput {
    /**
     * 
     * @type {string}
     * @memberof CreateMemberInput
     */
    name: any;
    /**
     * 
     * @type {string}
     * @memberof CreateMemberInput
     */
    email: any;
    /**
     * 
     * @type {UserInfoAddress}
     * @memberof CreateMemberInput
     */
    address: any;
    /**
     * 
     * @type {string}
     * @memberof CreateMemberInput
     */
    phone: any;
    /**
     * 
     * @type {string}
     * @memberof CreateMemberInput
     */
    password: any;
    /**
     * 
     * @type {string}
     * @memberof CreateMemberInput
     */
    planType: any;
}
