/* tslint:disable */
/* eslint-disable */
/**
 * bnm
 * Books N More's API
 *
 * OpenAPI spec version: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CreatePlanBody
 */
export interface CreatePlanBody {
    /**
     * 
     * @type {string}
     * @memberof CreatePlanBody
     */
    authKey?: any;
    /**
     * 
     * @type {string}
     * @memberof CreatePlanBody
     */
    planType?: any;
}
