/* tslint:disable */
/* eslint-disable */
/**
 * bnm
 * Books N More's API
 *
 * OpenAPI spec version: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ErrorDataErrorStrings
 */
export interface ErrorDataErrorStrings {
    /**
     * 
     * @type {string}
     * @memberof ErrorDataErrorStrings
     */
    _0: any;
    /**
     * 
     * @type {string}
     * @memberof ErrorDataErrorStrings
     */
    _1: any;
    /**
     * 
     * @type {string}
     * @memberof ErrorDataErrorStrings
     */
    _2: any;
    /**
     * 
     * @type {string}
     * @memberof ErrorDataErrorStrings
     */
    _3: any;
    /**
     * 
     * @type {string}
     * @memberof ErrorDataErrorStrings
     */
    _4: any;
    /**
     * 
     * @type {string}
     * @memberof ErrorDataErrorStrings
     */
    _5: any;
    /**
     * 
     * @type {string}
     * @memberof ErrorDataErrorStrings
     */
    _6: any;
    /**
     * 
     * @type {string}
     * @memberof ErrorDataErrorStrings
     */
    _7: any;
    /**
     * 
     * @type {string}
     * @memberof ErrorDataErrorStrings
     */
    _8: any;
    /**
     * 
     * @type {string}
     * @memberof ErrorDataErrorStrings
     */
    _9: any;
    /**
     * 
     * @type {string}
     * @memberof ErrorDataErrorStrings
     */
    _10: any;
    /**
     * 
     * @type {string}
     * @memberof ErrorDataErrorStrings
     */
    _11: any;
    /**
     * 
     * @type {string}
     * @memberof ErrorDataErrorStrings
     */
    _12: any;
    /**
     * 
     * @type {string}
     * @memberof ErrorDataErrorStrings
     */
    _13: any;
    /**
     * 
     * @type {string}
     * @memberof ErrorDataErrorStrings
     */
    _14: any;
    /**
     * 
     * @type {string}
     * @memberof ErrorDataErrorStrings
     */
    _15: any;
    /**
     * 
     * @type {string}
     * @memberof ErrorDataErrorStrings
     */
    _16: any;
    /**
     * 
     * @type {string}
     * @memberof ErrorDataErrorStrings
     */
    _17: any;
    /**
     * 
     * @type {string}
     * @memberof ErrorDataErrorStrings
     */
    _18: any;
    /**
     * 
     * @type {string}
     * @memberof ErrorDataErrorStrings
     */
    _19: any;
    /**
     * 
     * @type {string}
     * @memberof ErrorDataErrorStrings
     */
    _20: any;
    /**
     * 
     * @type {string}
     * @memberof ErrorDataErrorStrings
     */
    _21: any;
    /**
     * 
     * @type {string}
     * @memberof ErrorDataErrorStrings
     */
    _22: any;
}
