/* tslint:disable */
/* eslint-disable */
/**
 * bnm
 * Books N More's API
 *
 * OpenAPI spec version: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PlanInfo
 */
export interface PlanInfo {
    /**
     * 
     * @type {number}
     * @memberof PlanInfo
     */
    deposit: any;
    /**
     * 
     * @type {number}
     * @memberof PlanInfo
     */
    errorCode: any;
    /**
     * 
     * @type {number}
     * @memberof PlanInfo
     */
    joiningFee: any;
    /**
     * 
     * @type {Array&lt;PlanInfoPlans&gt;}
     * @memberof PlanInfo
     */
    plans: any;
}
