/* tslint:disable */
/* eslint-disable */
/**
 * bnm
 * Books N More's API
 *
 * OpenAPI spec version: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PlanInfoPlans
 */
export interface PlanInfoPlans {
    /**
     * 
     * @type {number}
     * @memberof PlanInfoPlans
     */
    cost: any;
    /**
     * 
     * @type {string}
     * @memberof PlanInfoPlans
     */
    duration: any;
    /**
     * 
     * @type {number}
     * @memberof PlanInfoPlans
     */
    numDeliveries: any;
    /**
     * 
     * @type {string}
     * @memberof PlanInfoPlans
     */
    planType: any;
}
