/* tslint:disable */
/* eslint-disable */
/**
 * bnm
 * Books N More's API
 *
 * OpenAPI spec version: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PlanData
 */
export interface PlanData {
    /**
     * 
     * @type {string}
     * @memberof PlanData
     */
    duration: any;
    /**
     * 
     * @type {number}
     * @memberof PlanData
     */
    nextRenewal: any;
    /**
     * 
     * @type {number}
     * @memberof PlanData
     */
    planId: any;
    /**
     * 
     * @type {string}
     * @memberof PlanData
     */
    canDelete: any;
    /**
     * 
     * @type {number}
     * @memberof PlanData
     */
    balanceDue: any;
}
