/* tslint:disable */
/* eslint-disable */
/**
 * bnm
 * Books N More's API
 *
 * OpenAPI spec version: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SearchData
 */
export interface SearchData {
    /**
     * 
     * @type {number}
     * @memberof SearchData
     */
    startBook?: any;
    /**
     * 
     * @type {number}
     * @memberof SearchData
     */
    booksMatched?: any;
    /**
     * 
     * @type {number}
     * @memberof SearchData
     */
    endBook?: any;
    /**
     * 
     * @type {number}
     * @memberof SearchData
     */
    errorCode?: any;
    /**
     * 
     * @type {Array&lt;BookData&gt;}
     * @memberof SearchData
     */
    books?: any;
}
