/* tslint:disable */
/* eslint-disable */
/**
 * bnm
 * Books N More's API
 *
 * OpenAPI spec version: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    errorCode: any;
    /**
     * 
     * @type {UserInfo}
     * @memberof User
     */
    userDetails?: any;
    /**
     * 
     * @type {Array&lt;PlanData&gt;}
     * @memberof User
     */
    plans?: any;
    /**
     * 
     * @type {UserBooks}
     * @memberof User
     */
    books?: any;
}
